### ISSUE TITLE
Cannot install Sublime text GLua highlighter

### ISSUE THREAD

**Issue by dvdvideo1234** [FPtje/Sublime-GLua-Highlight#39]
1. Installing through the package manager ( after adding `ignored_packages` )
![image](https://user-images.githubusercontent.com/9112662/59681947-ccb93300-91dd-11e9-9de6-248ecb9af7ef.png)

2. Cloning [this repo](https://github.com/FPtje/Sublime-GLua-Highlight) in
`C:\Users\ddobromirov\AppData\Roaming\Sublime Text 3\Packages`

**Comment by FPtje** [comment]
The error is a syntax error in your own preferences file. That can prevent the GLua highlighter from installing, but also any other package. Open sublime's settings and find the error there.

**Comment by dvdvideo1234** [comment]
The file contains only `"ignored_packages": ["Vintage", "Lua"]` ( with CR, nad LF for windows ) at the and.
There is no mistake inside.

**Comment by FPtje** [comment]
Shouldn't that file be a json object though? Where are the surrounding `{}` characters?

**Comment by dvdvideo1234** [comment]
@FPtje Adding `Lua` to this option seems irrelevant as the repo works without it.
![image](https://user-images.githubusercontent.com/9112662/59690213-aef1cb00-91e9-11e9-9418-6bba9017707b.png)

**Comment by FPtje** [comment]
I just tried installing the plugin. It worked for me. I found that when removing `Lua` fro `ignored_packages`, that the built in Lua highlighter takes over. Adding it to `ignored_packages` initially shows the error in your screenshot, but that is resolved by either setting the syntax to GMod Lua or restarting sublime.

**Comment by dvdvideo1234** [comment]
I used JSON validator websites like [this one here](https://jsonformatter.curiousconcept.com/), which showed me that the error is not in line `1` as sublime persisted, but instead, I had to remove one comma from the last key-value pair:
```json
{
	"color_scheme": "Packages/Color Scheme - Default/Monokai.sublime-color-scheme",
	"ignored_packages":
	[
		"Vintage", "Lua"
	],

    // The number of spaces a tab is considered equal to
    "tab_size": 2,

    // Trims white space added by auto_indent when moving the caret off the
    // line.
    "trim_automatic_white_space": true,

    // Set to true to removing trailing white space on save
    "trim_trailing_white_space_on_save": true
}
```

**Comment by dvdvideo1234** [comment]
Sublime still persist like the last error that has no Lua settings, which is strange :D.

**Comment by dvdvideo1234** [comment]
In fact in Lua.sublime-settings I have:
```json
{
	"extensions":
	[
		"lua"
	]
}

```
